#! /bin/sh
rm -f check
if [ -f .ingress/tf.tfvars ]
then
    EML="$(cat .ingress/tf.tfvars | grep 'email' | sed -e 's/cloudflare_email = //g; s/\"//g')"
    export EML
    ACK="$(cat .ingress/tf.tfvars | grep 'access' | sed -e 's/aws_access_key = //g; s/\"//g')"
    SCK="$(cat .ingress/tf.tfvars | grep 'secret' | sed -e 's/aws_secret_key = //g; s/\"//g')"
    CFA="$(cat .ingress/tf.tfvars | grep 'api' | sed -e 's/cloudflare_api_key = //g; s/\"//g')"
    printf "\033c"
    echo "*************************************************************************************************"
    echo "***********                                                                           ***********"
    echo "***********                         CONSTRUCTOR WEB 'VIM-v2.0'                        ***********"
    echo "***********                                                                           ***********"
    echo "***********                       https://academiavim.com/script                      ***********"
    echo "***********                                                                           ***********"
    echo "===========                                                                           ==========="
    echo "===========                           !  A T E N C I Ó N  !                           ==========="
    echo "===========                                                                           ==========="
    echo "================================================================================================="
    echo ""
    echo "           Ya se han encontrado las siguientes Credenciales de acceso en este perfil:       "
    echo ""
    echo "           'CORREO ELECTRÓNICO'  de Cloudflare       =  $EML                                  "
    echo "           'API KEY'  de Cloudflare                  =  $CFA                                  "
    echo "           'ID DE CLAVE DE ACCESO'  de Amazon AWS    =  $ACK "
    echo "           'CLAVE DE ACCESO SECRETA'  de Amazon AWS  =  $SCK                                  "
    echo ""
    echo -n "   ¿ Que Deseas Hacer ?              "
    echo ""
    echo ""
    echo -n " -  Escribe 'continuar' para desplegar un nuevo servidor con estas Credenciales...                      "
    echo ""
    echo -n " -  Escribe 'cambiar' para crear unas credenciales nuevas...                   "
    echo ""
    echo -n " -  Escribe 'salir' para cancelar esta operación  [ salir / cambiar / continuar ]: "
    read INPUT
    if [ $INPUT = "cambiar" -o $INPUT = "Cambiar" -o $INPUT = "CAMBIAR" ]
    then
        printf "\033c"
        echo "*************************************************************************************************"
        echo "***********                                                                           ***********"
        echo "***********                         CONSTRUCTOR WEB 'VIM-v2.0'                        ***********"
        echo "***********                                                                           ***********"
        echo "***********                       https://academiavim.com/script                      ***********"
        echo "***********                                                                           ***********"
        echo "===========                                                                           ==========="
        echo "===========                           !  A T E N C I Ó N  !                           ==========="
        echo "===========                                                                           ==========="
        echo "================================================================================================="
        echo ""
        echo -n " -  ¿Seguro que quieres BORRAR estas Credenciales y crear unas NUEVAS?  [ si / no ]: "
        read INPUT
        if [ $INPUT = "s" -o $INPUT = "si" -o $INPUT = "sí" -o $INPUT = "S" -o $INPUT = "SI" -o $INPUT = "SÍ" ]
        then
            rm -f -r .ingress/
            wget -qO first https://raw.githubusercontent.com/iversating/vimzwei/master/first2
            sh first
        else
            wget -qO check https://raw.githubusercontent.com/iversating/vimzwei/master/check2
            sh check
        fi
    elif [ $INPUT = "salir" -o $INPUT = "Salir" -o $INPUT = "SALIR" ]
    then
        printf "\033c"
        echo "*************************************************************************************************"
        echo "***********                                                                           ***********"
        echo "***********                         CONSTRUCTOR WEB 'VIM-v2.0'                        ***********"
        echo "***********                                                                           ***********"
        echo "***********                       https://academiavim.com/script                      ***********"
        echo "***********                                                                           ***********"
        echo "===========                                                                           ==========="
        echo "===========                          !  C A N C E L A D O  !                          ==========="
        echo "===========                                                                           ==========="
        echo "===========                                                                           ==========="
        echo "================================================================================================="
        echo "***********                                                                           ***********"
        echo "***********                                                                           ***********" 
        echo "***********     Para ejecutar de nuevo el Script escribe 'sh vim' y oprime [enter]    ***********"
        echo "***********                                                                           ***********"
        echo "***********                                                                           ***********"
        echo "*************************************************************************************************"
        echo ""
        exit
    else
        wget -qO variables https://raw.githubusercontent.com/iversating/vimzwei/master/variables2
        sh variables
    fi
else
    wget -qO first https://raw.githubusercontent.com/iversating/vimzwei/master/first2
    sh first
fi
