#! /bin/sh
rm -f first
printf "\033c"
if [ ! -f .ingress/centos ]
then
    echo "*************************************************************************************************"
    echo "***********                                                                           ***********"
    echo "***********                         CONSTRUCTOR WEB 'VIM 2.0'                         ***********"
    echo "***********                                                                           ***********"
    echo "***********                    https://ventasimpactantes.com/script                   ***********"
    echo "***********                                                                           ***********"
    echo "================================================================================================="
    echo "===========                                                                           ==========="
    echo "===========                          ! I M P O R T A N T E !                          ==========="
    echo "===========                                                                           ==========="
    echo "================================================================================================="
    echo ""
    echo "           Para que este script funcione correctamente, acepta los términos de 'Centos7'         "
    echo ""
    echo "           Si aún no lo haces, entra al enlace con tu cuenta de AWS y haz clic en:               "
    echo ""
    echo "                                    ' A c c e p t   T e r m s '                                  "
    echo ""
    echo "           Luego regresa aquí para continuar. si no ves el botón es porque ya aceptaste.         "
    echo ""
    echo ""
    echo "           Acepta Términos Aquí: https://ventasimpactantes.com/aceptar-terminos-centos7          "
    echo ""
    echo ""
    echo ""
    echo -n " *  ¡SI NO HAZ REALIZADO EL PASO ANTERIOR, ESTE SCRIPT NO FUNCIONARÁ! * "
    echo ""
    echo ""
    echo ""
    echo -n " -  ¿Ya aceptaste los términos para 'Centos7' en la página anterior?  [ si / no ]: "
    read INPUT
    if [ $INPUT = "s" -o $INPUT = "si" -o $INPUT = "sí" -o $INPUT = "S" -o $INPUT = "SI" -o $INPUT = "SÍ" ]
    then
        mkdir .ingress/
        touch .ingress/centos
        wget -qO variables https://raw.githubusercontent.com/iversating/vimzwei/master/variables2
        sh variables
    else
        printf "\033c"
        echo "*************************************************************************************************"
        echo "***********                                                                           ***********"
        echo "***********                         CONSTRUCTOR WEB 'VIM 2.0'                         ***********"
        echo "***********                                                                           ***********"
        echo "***********                    https://ventasimpactantes.com/script                   ***********"
        echo "***********                                                                           ***********"
        echo "================================================================================================="
        echo "===========                                                                           ==========="
        echo "===========                  ! V U E L V E  A  I N T E N T A R L O !                  ==========="
        echo "===========                                                                           ==========="
        echo "================================================================================================="
        echo ""
        echo "    Para poder continuar, asegúrate de ir a la siguiente página y hacer clic en el botón de:     "
        echo ""
        echo "                                        ' Accept Terms '                                         "
        echo ""
        echo "    Luego vuelve aquí y ejecuta de nuevo el script escribiendo 'wget -qO vim shvim2.tk && sh vim'"
        echo ""
        echo ""
        echo "    Acepta Términos Aquí: https://ventasimpactantes.com/aceptar-terminos-centos7                 "
        echo ""
        echo ""
        echo "================================================================================================="
        echo ""
        echo ""
        exit
    fi
else
    wget -qO variables https://raw.githubusercontent.com/iversating/vimzwei/master/variables2
    sh variables
fi
