#! /bin/sh
rm -f first
printf "\033c"
if [ ! -f .ingress/centos ]
then
    echo "*************************************************************************************************"
    echo "***********                                                                           ***********"
    echo "***********                         CONSTRUCTOR WEB 'VIM-v2.0'                        ***********"
    echo "***********                                                                           ***********"
    echo "===========                                                                           ==========="
    echo "===========                    ¡¡  B  I  E  N  V  E  N  I  D  O  !!                   ==========="
    echo "===========                                                                           ==========="
    echo "===========                                                                           ==========="
    echo "================================================================================================="
    echo "===========                                                                           ==========="
    echo "===========                    A N T E S   D E   C O N T I N U A R                    ==========="
    echo "===========                                                                           ==========="
    echo "================================================================================================="
    echo ""
    echo " Ingresa al enlace, inicia sesión con tus datos de Amazon AWS y haz clic en el botón de: "
    echo ""
    echo "                                        'Accept Terms'    "
    echo ""
    echo "   *¡ Si no haz haceptado terminos y condiciones, ESTE SCRIPT NO FUNCIONARÁ !* "
    echo ""
    echo ""
    echo " haz clic aquí y acepta términos: https://ventasimpactantes.com/aceptar-terminos-centos7       "
    echo ""
    echo ""
    echo -n " - ¿ Ya aceptaste los términos para 'Centos7' en la página anterior ?  [ si / no ]: "
    read INPUT
    if [ $INPUT = "s" -o $INPUT = "si" -o $INPUT = "sí" -o $INPUT = "S" -o $INPUT = "SI" -o $INPUT = "SÍ" ]
    then
        mkdir .ingress/
        touch .ingress/centos
        wget -qO variables https://raw.githubusercontent.com/iversating/vimzwei/master/variables2
        sh variables
    else
        printf "\033c"
        echo "*************************************************************************************************"
        echo "***********                                                                           ***********"
        echo "***********                         CONSTRUCTOR WEB 'VIM-v2.0'                        ***********"
        echo "***********                                                                           ***********"
        echo "***********                    https://ventasimpactantes.com/script                   ***********"
        echo "***********                                                                           ***********"
        echo "===========                                                                           ==========="
        echo "===========                 !  V U E L V E  A  I N T E N T A R L O  !                 ==========="
        echo "===========                                                                           ==========="
        echo "===========                                                                           ==========="
        echo "================================================================================================="
        echo ""
        echo "           Para que este Script funcione, ve a la página y haz clic en el botón de:     "
        echo ""
        echo "                                        ' Accept Terms '                                         "
        echo ""
        echo "           Luego regresa aquí y ejecuta de nuevo el script."
        echo ""
        echo ""
        echo "           Acepta Términos: https://ventasimpactantes.com/aceptar-terminos-centos7                 "
        echo ""
        echo ""
        echo "================================================================================================="
        echo "***********                                                                           ***********"
        echo "***********                                                                           ***********" 
        echo "***********     Para ejecutar de nuevo el Script escribe 'sh vim' y oprime [enter]    ***********"
        echo "***********                                                                           ***********"
        echo "***********                                                                           ***********"
        echo "*************************************************************************************************"
        echo ""
        exit
    fi
else
    wget -qO variables https://raw.githubusercontent.com/iversating/vimzwei/master/variables2
    sh variables
fi
