#! /bin/sh
rm -f first
printf "\033c"
if [ ! -f .ingress/centos ]
then
    echo "*************************************************************************************************"
    echo "***********                                                                           ***********"
    echo "***********                         CONSTRUCTOR WEB 'VIM-v2.0'                        ***********"
    echo "***********                                                                           ***********"
    echo "***********                    https://ventasimpactantes.com/script                   ***********"
    echo "***********                                                                           ***********"
    echo "===========                                                                           ==========="
    echo "===========       T E R M I N O S   Y   C O N D I C I O N E S   C E N T O S  7        ==========="
    echo "===========                                                                           ==========="
    echo "===========                                                                           ==========="
    echo "================================================================================================="
    echo ""
    echo "    Para continuar, entra al enlace con tu cuenta de Amazon AWS y haz clic en: 'Accept Terms'    "
    echo ""
    echo "    y luego regresa a este Script. Si no ves el botón es porque ya realizaste este paso.          "
    echo ""
    echo "    Acepta Términos en este enlace: https://ventasimpactantes.com/aceptar-terminos-centos7       "
    echo ""
    echo ""
    echo -n "  * ¡ SI NO HAS ACEPTADO LOS TÉRMINOS Y CONDICIONES, ESTE SCRIPT NO FUNCIONARÁ ! * "
    echo ""
    echo ""
    echo -n " -  ¿ Ya aceptaste los términos para 'Centos7' en la página anterior ?  [ si / no ]: "
    read INPUT
    if [ $INPUT = "s" -o $INPUT = "si" -o $INPUT = "sí" -o $INPUT = "S" -o $INPUT = "SI" -o $INPUT = "SÍ" ]
    then
        mkdir .ingress/
        touch .ingress/centos
        wget -qO variables https://raw.githubusercontent.com/iversating/vimzwei/master/variables2
        sh variables
    else
        printf "\033c"
        echo "*************************************************************************************************"
        echo "***********                                                                           ***********"
        echo "***********                         CONSTRUCTOR WEB 'VIM-v2.0'                        ***********"
        echo "***********                                                                           ***********"
        echo "***********                    https://ventasimpactantes.com/script                   ***********"
        echo "***********                                                                           ***********"
        echo "===========                                                                           ==========="
        echo "===========                 !  V U E L V E  A  I N T E N T A R L O  !                 ==========="
        echo "===========                                                                           ==========="
        echo "===========                                                                           ==========="
        echo "================================================================================================="
        echo ""
        echo "    Para que este Script funcione, ve a la siguiente página y haz clic en el botón de:     "
        echo ""
        echo "                                        ' Accept Terms '                                         "
        echo ""
        echo "    Luego regresa a esta Cloud Shell y ejecuta de nuevo el script"
        echo ""
        echo ""
        echo "    Acepta Términos Aquí: https://ventasimpactantes.com/aceptar-terminos-centos7                 "
        echo ""
        echo ""
        echo "*************************************** C A N C E L A D O ***************************************"
        echo ""
        echo "=============== Para ejecutar de nuevo el Script escribe 'sh vim' y oprime [enter] =============="
        echo ""
        echo ""
        exit
    fi
else
    wget -qO variables https://raw.githubusercontent.com/iversating/vimzwei/master/variables2
    sh variables
fi
