#! /bin/sh
rm -f variables
if [ ! -f .ingress/tf.tfvars ]
then
    printf "\033c"
    echo "*************************************************************************************************"
    echo "***********                                                                           ***********"
    echo "***********                      CONSTRUCTOR WEB 'Script-VIM_v2.0'                    ***********"
    echo "***********                                                                           ***********"
    echo "***********                       https://academiavim.com/script                      ***********"
    echo "***********                                                                           ***********"
    echo "===========                                                                           ==========="
    echo "===========                         !  C O M E N C E M O S  !                         ==========="
    echo "===========                                                                           ==========="
    echo "================================================================================================="
    echo ""
    echo "                              COMPLETA TUS CREDENCIALES PERSONALES                               "
    echo ""   
    echo -n " - Escribe el 'CORREO' de tu cuenta de Cloudflare y luego oprime [enter]      = "
    read INPUT
    if [ $INPUT ]; then
        EML="$INPUT"
        export EML
    fi
    echo ""
    echo -n " - Pega la 'API KEY' de Cloudflare ('Ctrl V' en tu teclado) y oprime [enter]  = "
    read INPUT
    if [ $INPUT ]; then
        CFAPI="$INPUT"
        export CFAPI
    fi
    echo ""
    echo -n " - Pega el 'ID DE CLAVE DE ACCESO' de Amazon AWS, (Ctrl V) y oprime [enter]   = "
    read INPUT
    if [ $INPUT ]; then
        accesskey="$INPUT"
        export accesskey
    fi
    echo ""
    echo -n " - Pega aquí la 'CLAVE DE ACCESO SECRETA' de Amazon AWS, (Ctrl V) y [enter]   = "
    read INPUT
    if [ $INPUT ]; then
        secretkey="$INPUT"
        export secretkey
    fi
    echo ""
    echo -n " - Escribe tu 'DOMINIO' registrado, en minúscula, sin www y oprime [enter]    = "
    read INPUT
    if [ $INPUT ]; then
        MYDOMAIN="$INPUT"
        export MYDOMAIN
    fi
    MYDBNAME=$(echo "$MYDOMAIN" | sed 's/\([[:alnum:]][[:alnum:]]*\)\.\([[:graph:]][[:graph:]]*\)/\1/g')
    export MYDBNAME
    MYSERVER=$(echo "$MYDOMAIN" | sed 's/\.//g')
    export MYSERVER
    printf "\033c"
    echo "*************************************************************************************************"
    echo "***********                                                                           ***********"
    echo "***********                      CONSTRUCTOR WEB 'Script-VIM_v2.0'                    ***********"
    echo "***********                                                                           ***********"
    echo "***********                       https://academiavim.com/script                      ***********"
    echo "***********                                                                           ***********"
    echo "===========                                                                           ==========="
    echo "===========                          !  R E V I S E M O S  !                          ==========="
    echo "===========                                                                           ==========="
    echo "================================================================================================="
    echo ""
    echo "                            ESTAS SON LAS CREDENCIALES QUE INGRESASTE:                           "
    echo ""
    echo "           'CORREO ELECTRÓNICO' de Cloudflare  = $EML                                   "
    echo "           'API KEY' de Cloudflare             = $CFAPI                                 "
    echo "           'ID DE CLAVE DE ACCESO' de AWS      = $accesskey                             "
    echo "           'CLAVE DE ACCESO SECRETA' de AWS    = $secretkey                             "
    echo "           'DOMINIO' para crear tu página web  = $MYDOMAIN                              "
    echo ""
    echo -n "   ¿ Son Correctas Estas Credenciales ?                                              "
    echo ""
    echo ""
    echo -n " -  Escribe 'crear' para ejecutar la construcción del servidor..."
    echo ""
    echo -n " -  Escribe 'cambiar' para editar las Credenciales de nuevo...                   "
    echo ""
    echo -n " -  Escribe 'salir' para cancelar este script  [ salir / cambiar / crear ]: "   
    read INPUT
    if [ $INPUT = "crear" -o $INPUT = "CREAR" -o $INPUT = "Crear" ]
    then
        wget -qO archivos https://raw.githubusercontent.com/iversating/vimzwei/master/archivos2
        sh archivos
    elif [ $INPUT = "salir" -o $INPUT = "Salir" -o $INPUT = "SALIR" ]
    then
        printf "\033c"
        echo "*************************************************************************************************"
        echo "***********                                                                           ***********"
        echo "***********                      CONSTRUCTOR WEB 'Script-VIM_v2.0'                    ***********"
        echo "***********                                                                           ***********"
        echo "***********                       https://academiavim.com/script                      ***********"
        echo "***********                                                                           ***********"
        echo "===========                                                                           ==========="
        echo "===========                          !  C A N C E L A D O  !                          ==========="
        echo "===========                                                                           ==========="
        echo "===========                                                                           ==========="
        echo "================================================================================================="
        echo "***********                                                                           ***********"
        echo "***********                                                                           ***********" 
        echo "***********     Para ejecutar de nuevo el Script escribe 'sh vim' y oprime [enter]    ***********"
        echo "***********                                                                           ***********"
        echo "***********                                                                           ***********"
        echo "*************************************************************************************************"
        echo ""
        exit
    else
        wget -qO variables https://raw.githubusercontent.com/iversating/vimzwei/master/variables2
        sh variables
    fi
else
    printf "\033c"
    EML="$(cat .ingress/tf.tfvars | grep 'email' | sed -e 's/cloudflare_email = //g; s/\"//g')"
    export EML
    ACK="$(cat .ingress/tf.tfvars | grep 'access' | sed -e 's/aws_access_key = //g; s/\"//g')"
    SCK="$(cat .ingress/tf.tfvars | grep 'secret' | sed -e 's/aws_secret_key = //g; s/\"//g')"
    CFAPI="$(cat .ingress/tf.tfvars | grep 'api' | sed -e 's/cloudflare_api_key = //g; s/\"//g')"
    export CFAPI
    echo "*************************************************************************************************"
    echo "***********                                                                           ***********"
    echo "***********                      CONSTRUCTOR WEB 'Script-VIM_v2.0'                    ***********"
    echo "***********                                                                           ***********"
    echo "***********                       https://academiavim.com/script                      ***********"
    echo "***********                                                                           ***********"
    echo "===========                                                                           ==========="
    echo "===========                        !  C O N T I N U E M O S  !                        ==========="
    echo "===========                                                                           ==========="
    echo "================================================================================================="
    echo ""
    echo "                              COMPLETA TUS CREDENCIALES PERSONALES                               "
    echo ""
    echo ""
    echo -n " - Este es tu 'CORREO ELECTRÓNICO' de Cloudflare         = $EML"
    echo ""
    echo ""
    echo -n " - Esta es la 'API KEY' de Cloudflare                    = $CFAPI"
    echo ""
    echo ""
    echo -n " - Este es el 'ID DE CLAVE DE ACCESO' de Amazon AWS      = $ACK"
    echo ""
    echo ""
    echo -n " - Esta es la 'CLAVE DE ACCESO SECRETA' de Amazon AWS    = $SCK"
    echo ""
    echo ""
    echo -n " - Escribe tu 'DOMINIO' en minúscula y sin www, [enter]  = "
    read INPUT
    if [ $INPUT ]; then
        MYDOMAIN="$INPUT"
        export MYDOMAIN
    fi
    MYDBNAME=$(echo "$MYDOMAIN" | sed 's/\([[:alnum:]][[:alnum:]]*\)\.\([[:graph:]][[:graph:]]*\)/\1/g')
    export MYDBNAME
    MYSERVER=$(echo "$MYDOMAIN" | sed 's/\.//g')
    export MYSERVER
    EML="$EML"
    export EML
    accesskey="$ACK"
    export accesskey
    secretkey="$SCK"
    export secretkey
    printf "\033c"
    echo "*************************************************************************************************"
    echo "***********                                                                           ***********"
    echo "***********                      CONSTRUCTOR WEB 'Script-VIM_v2.0'                    ***********"
    echo "***********                                                                           ***********"
    echo "***********                       https://academiavim.com/script                      ***********"
    echo "***********                                                                           ***********"
    echo "===========                                                                           ==========="
    echo "===========                          !  R E V I S E M O S  !                          ==========="
    echo "===========                                                                           ==========="
    echo "================================================================================================="
    echo ""
    echo "                             ESTAS SON LAS CREDENCIALES QUE INGRESASTE:                          "
    echo ""
    echo "           'CORREO ELECTRÓNICO' de Cloudflare  = $EML                               "
    echo "           'API KEY' de Cloudflare             = $CFAPI                                   "
    echo "           'ID DE CLAVE DE ACCESO' de AWS      = $ACK                                   "
    echo "           'CLAVE DE ACCESO SECRETA' de AWS    = $SCK                                   "
    echo "           'DOMINIO' para crear tu página web  = $MYDOMAIN                              "
    echo ""
    echo -n "   ¿ Son Correctas Estas Credenciales ?                                                        "
    echo ""
    echo ""
    echo -n " -  Escribe 'crear' para ejecutar la construcción del servidor..."
    echo ""
    echo -n " -  Escribe 'cambiar' para editar las credenciales...                   "
    echo ""
    echo -n " -  Escribe 'salir' para cancelar este script  [ salir / cambiar / crear ]: "   
    read INPUT
    if [ $INPUT = "crear" -o $INPUT = "CREAR" -o $INPUT = "Crear" ]
    then
        wget -qO archivos https://raw.githubusercontent.com/iversating/vimzwei/master/archivos2
        sh archivos
    elif [ $INPUT = "salir" -o $INPUT = "Salir" -o $INPUT = "SALIR" ]
    then
        printf "\033c"
        echo "*************************************************************************************************"
        echo "***********                                                                           ***********"
        echo "***********                     CONSTRUCTOR WEB 'Script-VIM_v2.0'                     ***********"
        echo "***********                                                                           ***********"
        echo "***********                       https://academiavim.com/script                      ***********"
        echo "***********                                                                           ***********"
        echo "===========                                                                           ==========="
        echo "===========                          !  C A N C E L A D O  !                          ==========="
        echo "===========                                                                           ==========="
        echo "================================================================================================="
        echo "***********                                                                           ***********"
        echo "***********                                                                           ***********" 
        echo "***********     Para ejecutar de nuevo el Script escribe 'sh vim' y oprime [enter]    ***********"
        echo "***********                                                                           ***********"
        echo "***********                                                                           ***********"
        echo "*************************************************************************************************"
        echo ""
        exit
    else
        wget -qO variables https://raw.githubusercontent.com/iversating/vimzwei/master/variables2
        sh variables
    fi
fi
